name: "Build and push DockerHub images"

on:
  workflow_dispatch:  # 只允许手动触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: "Build and push image"
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKERHUB_REPOSITORY: ${{ secrets.DOCKER_USERNAME }}/music-player:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Push images to Docker hub
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64, linux/arm64
          tags: ${{ env.DOCKERHUB_REPOSITORY }}
